version: '3.8'

services:
  frontend:
    build:
      context: ./questionbank.client
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    build:
      context: ./
    ports:
      - '5000:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__QuestionBank=Server=postgres;Port=5432;Database=QuestionBank;User Id=questionbank;Password=postgres        
      
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: questionbank
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: QuestionBank
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
