const data = [
  {
    categoryId: 1,
    categoryName: "Tadeo",
    minRequiredReviewer: 1,
    reviewers: "McCall Municipal Airport",
    approvers: "Andalax",
  },
  {
    categoryId: 2,
    categoryName: "Gwenneth",
    minRequiredReviewer: 2,
    reviewers: "Annemasse Airport",
    approvers: "Bytecard",
  },
  {
    categoryId: 3,
    categoryName: "Alameda",
    minRequiredReviewer: 3,
    reviewers: "Hickory Regional Airport",
    approvers: "Hatity",
  },
  {
    categoryId: 4,
    categoryName: "Gertrud",
    minRequiredReviewer: 4,
    reviewers: "Statesville Regional Airport",
    approvers: "Konklux",
  },
  {
    categoryId: 5,
    categoryName: "Thorvald",
    minRequiredReviewer: 5,
    reviewers: "Caia Airport",
    approvers: "Sub-Ex",
  },
  {
    categoryId: 6,
    categoryName: "Wilona",
    minRequiredReviewer: 6,
    reviewers: "Luhansk International Airport",
    approvers: "Biodex",
  },
  {
    categoryId: 7,
    categoryName: "Lamond",
    minRequiredReviewer: 7,
    reviewers: "Wilmington International Airport",
    approvers: "Stringtough",
  },
  {
    categoryId: 8,
    categoryName: "Daffy",
    minRequiredReviewer: 8,
    reviewers: "28 de Noviembre Airport",
    approvers: "Prodder",
  },
  {
    categoryId: 9,
    categoryName: "Alaric",
    minRequiredReviewer: 9,
    reviewers: "Hamilton Island Airport",
    approvers: "Wrapsafe",
  },
  {
    categoryId: 10,
    categoryName: "Vern",
    minRequiredReviewer: 10,
    reviewers: "Atatürk International Airport",
    approvers: "Tampflex",
  },
  {
    categoryId: 11,
    categoryName: "Vina",
    minRequiredReviewer: 11,
    reviewers: "Santa Rosa de Copán Airport",
    approvers: "Tempsoft",
  },
  {
    categoryId: 12,
    categoryName: "Tootsie",
    minRequiredReviewer: 12,
    reviewers: "Raba Raba Airport",
    approvers: "Viva",
  },
  {
    categoryId: 13,
    categoryName: "Todd",
    minRequiredReviewer: 13,
    reviewers: "Broadus Airport",
    approvers: "Stringtough",
  },
  {
    categoryId: 14,
    categoryName: "Kayley",
    minRequiredReviewer: 14,
    reviewers: "Stawell Airport",
    approvers: "Andalax",
  },
  {
    categoryId: 15,
    categoryName: "Livvy",
    minRequiredReviewer: 15,
    reviewers: "Warroad International Memorial Airport",
    approvers: "Latlux",
  },
  {
    categoryId: 16,
    categoryName: "Ellswerth",
    minRequiredReviewer: 16,
    reviewers: "Bandanaira Airport",
    approvers: "Namfix",
  },
  {
    categoryId: 17,
    categoryName: "Everard",
    minRequiredReviewer: 17,
    reviewers: "Qeqertarsuaq Heliport",
    approvers: "Quo Lux",
  },
  {
    categoryId: 18,
    categoryName: "Bertha",
    minRequiredReviewer: 18,
    reviewers: "Opapimiskan Lake Airport",
    approvers: "Fintone",
  },
  {
    categoryId: 19,
    categoryName: "Justine",
    minRequiredReviewer: 19,
    reviewers: "Mansehra Airport",
    approvers: "Otcom",
  },
  {
    categoryId: 20,
    categoryName: "Burton",
    minRequiredReviewer: 20,
    reviewers: "Charlotte County Airport",
    approvers: "Otcom",
  },
];
export default data;
