export const apiRoutes = {
  signIn: "/auth/signIn",
  getUserInfo: "/useraccount",
  refreshToken: "/auth/refreshtoken",
  registerUser: "/useraccount",
  resetPassword: "/useraccount/resetpassword",
  uploadImage: "/useraccount/uploadimage",
  getImage: "/useraccount/getuserimage",
  getAllRoles: "/setting/roles",
  getAllCategory: "/QuestionCategory",
  getCategory: "/QuestionCategory",
  addCategory: "/QuestionCategory",
  updateCategory: "/QuestionCategory",
  getAllReviewer: "/UserAccount/reviewers",
  getAllApprover: "/UserAccount/Approvers",
  getAllMergeQuestion: "/Question",
  getOwnQuestionByStatus: "/Question/user/status",
  getQuestion: "/Question",
  getOwnQuestionView: "/question/user/view",
  getOwnQuestionEdit: "/question/user/edit",
  addQuestion: "/Question",
  updateOwnQuestion: "/Question/user/edit",
  getUsers: "/useraccount/users",
  getTags: "/tag",
  getAllReviewerQuestion: "/QuestionFeedBack/review/status",
  getAllApproverQuestion: "/QuestionFeedBack/approval/status",
  getOwnReviewComment: "/questionfeedback/comment",
  updateReviewAction: "/questionfeedback/review",
  resolveComment: "/questionfeedback/comment/resolve",

  getUserByUserId: (userId) => `/useraccount/${userId}`,
};
